# Generated by Django 4.0.2 on 2022-02-05 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='file',
            field=models.FileField(null=True, upload_to='films_image/', verbose_name=''),
        ),
    ]
