# Generated by Django 4.0.2 on 2022-02-05 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_alter_job_image_alter_job_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='description',
            field=models.CharField(max_length=500, null=True, verbose_name='Main description text'),
        ),
        migrations.AddField(
            model_name='job',
            name='video2',
            field=models.FileField(null=True, upload_to='videos/', verbose_name='video 2'),
        ),
        migrations.AlterField(
            model_name='job',
            name='image',
            field=models.ImageField(null=True, upload_to='images/', verbose_name='Main Image'),
        ),
        migrations.AlterField(
            model_name='job',
            name='summary',
            field=models.CharField(max_length=200, null=True, verbose_name='Main Summary text'),
        ),
        migrations.AlterField(
            model_name='job',
            name='video',
            field=models.FileField(null=True, upload_to='videos/', verbose_name='video 1'),
        ),
    ]
