# Generated by Django 4.0.2 on 2022-02-05 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_job_description_job_video2_alter_job_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='description',
            new_name='description1',
        ),
        migrations.AddField(
            model_name='job',
            name='description2',
            field=models.CharField(max_length=500, null=True, verbose_name='Second description text'),
        ),
    ]
