# Generated by Django 4.0.2 on 2022-02-06 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='index',
            name='headervideo',
            field=models.FileField(null=True, upload_to='videos/', verbose_name='header video'),
        ),
    ]
