# Generated by Django 4.0.2 on 2022-02-06 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_index_headervideo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index',
            name='headervideo',
            field=models.FileField(null=True, upload_to='videos/', verbose_name='Header video'),
        ),
    ]
