# Generated by Django 4.0.2 on 2022-02-06 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0013_alter_index_headervideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='index',
            name='AV',
            field=models.CharField(max_length=20, null=True, verbose_name='AV Services Text'),
        ),
        migrations.AddField(
            model_name='index',
            name='Acoustics',
            field=models.CharField(max_length=20, null=True, verbose_name='Acoustics Services Text'),
        ),
        migrations.AddField(
            model_name='index',
            name='IT',
            field=models.CharField(max_length=20, null=True, verbose_name='IT Services Text'),
        ),
        migrations.AddField(
            model_name='index',
            name='SoftwareandContent',
            field=models.CharField(max_length=20, null=True, verbose_name='Software & Content Services Text'),
        ),
    ]
