# Generated by Django 4.0.2 on 2022-02-06 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0014_index_av_index_acoustics_index_it_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AV', models.CharField(max_length=20, null=True, verbose_name='AV Services Text')),
                ('Acoustics', models.CharField(max_length=20, null=True, verbose_name='Acoustics Services Text')),
                ('IT', models.CharField(max_length=20, null=True, verbose_name='IT Services Text')),
                ('SoftwareandContent', models.CharField(max_length=20, null=True, verbose_name='Software & Content Services Text')),
            ],
        ),
        migrations.RemoveField(
            model_name='index',
            name='AV',
        ),
        migrations.RemoveField(
            model_name='index',
            name='Acoustics',
        ),
        migrations.RemoveField(
            model_name='index',
            name='IT',
        ),
        migrations.RemoveField(
            model_name='index',
            name='SoftwareandContent',
        ),
    ]
