# Generated by Django 4.0.2 on 2022-02-06 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0015_services_remove_index_av_remove_index_acoustics_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='AV',
            field=models.CharField(max_length=110, null=True, verbose_name='AV Services Text'),
        ),
        migrations.AlterField(
            model_name='services',
            name='Acoustics',
            field=models.CharField(max_length=110, null=True, verbose_name='Acoustics Services Text'),
        ),
        migrations.AlterField(
            model_name='services',
            name='IT',
            field=models.CharField(max_length=110, null=True, verbose_name='IT Services Text'),
        ),
        migrations.AlterField(
            model_name='services',
            name='SoftwareandContent',
            field=models.CharField(max_length=110, null=True, verbose_name='Software & Content Services Text'),
        ),
    ]
