# Generated by Django 4.0.2 on 2022-02-06 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0018_alter_services_av_alter_services_acoustics_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='services',
            old_name='Acoustics',
            new_name='acoustics',
        ),
        migrations.RenameField(
            model_name='services',
            old_name='AV',
            new_name='av',
        ),
        migrations.RenameField(
            model_name='services',
            old_name='IT',
            new_name='it',
        ),
        migrations.RenameField(
            model_name='services',
            old_name='SoftwareandContent',
            new_name='softwareandcontent',
        ),
    ]
