# Generated by Django 4.0.2 on 2022-02-06 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0019_rename_acoustics_services_acoustics_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project_Examples',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project1_text', models.CharField(max_length=130, null=True, verbose_name='project 1 text')),
                ('project1_image', models.ImageField(null=True, upload_to='images/', verbose_name='project 1 image')),
                ('project2_text', models.CharField(max_length=130, null=True, verbose_name='project 2 text')),
                ('project2_image', models.ImageField(null=True, upload_to='images/', verbose_name='project 2 image')),
                ('project3_text', models.CharField(max_length=130, null=True, verbose_name='project 3 text')),
                ('project3_image', models.ImageField(null=True, upload_to='images/', verbose_name='project 3 image')),
                ('project4_text', models.CharField(max_length=130, null=True, verbose_name='project 4 text')),
                ('project4_image', models.ImageField(null=True, upload_to='images/', verbose_name='project 4 image')),
            ],
        ),
    ]
