# Generated by Django 4.0.2 on 2022-02-06 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0020_project_examples'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_examples',
            name='project5_image',
            field=models.ImageField(null=True, upload_to='images/', verbose_name='project 5 image'),
        ),
        migrations.AddField(
            model_name='project_examples',
            name='project5_text',
            field=models.CharField(max_length=130, null=True, verbose_name='project 5 text'),
        ),
        migrations.AddField(
            model_name='project_examples',
            name='project6_image',
            field=models.ImageField(null=True, upload_to='images/', verbose_name='project 6 image'),
        ),
        migrations.AddField(
            model_name='project_examples',
            name='project6_text',
            field=models.CharField(max_length=130, null=True, verbose_name='project 6 text'),
        ),
    ]
