# Generated by Django 4.0.2 on 2022-02-06 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0021_project_examples_project5_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_examples',
            name='project1_size',
            field=models.CharField(max_length=130, null=True, verbose_name='project 1 size'),
        ),
    ]
