# Generated by Django 4.0.2 on 2022-02-06 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0024_project_examples_project_services_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=130, null=True, verbose_name='client name')),
                ('client_logo', models.ImageField(null=True, upload_to='images/', verbose_name='client logo')),
            ],
        ),
    ]
