# Generated by Django 4.0.2 on 2022-02-06 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0025_clients'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Job',
            new_name='Lab',
        ),
    ]
