# Generated by Django 4.0.2 on 2022-02-06 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0027_testimonials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonials',
            name='name',
            field=models.CharField(max_length=350, null=True, verbose_name='name of person'),
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='role',
            field=models.CharField(max_length=350, null=True, verbose_name='role or position'),
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='text',
            field=models.CharField(max_length=350, null=True, verbose_name='testimonial text'),
        ),
    ]
