# Generated by Django 4.0.2 on 2022-02-06 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0028_alter_testimonials_name_alter_testimonials_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonials',
            name='name',
            field=models.CharField(max_length=370, null=True, verbose_name='name of person'),
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='role',
            field=models.CharField(max_length=370, null=True, verbose_name='role or position'),
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='text',
            field=models.CharField(max_length=370, null=True, verbose_name='testimonial text'),
        ),
    ]
