# Generated by Django 4.0.2 on 2022-02-06 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0029_alter_testimonials_name_alter_testimonials_role_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Awards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=100, null=True, verbose_name='year')),
                ('category', models.CharField(max_length=100, null=True, verbose_name='entry')),
                ('award', models.CharField(max_length=100, null=True, verbose_name='award')),
                ('link', models.CharField(max_length=200, null=True, verbose_name='link')),
            ],
        ),
    ]
