# Generated by Django 4.0.2 on 2022-02-06 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0032_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='address',
        ),
        migrations.AddField(
            model_name='contact',
            name='country',
            field=models.CharField(max_length=250, null=True, verbose_name='country'),
        ),
        migrations.AddField(
            model_name='contact',
            name='postcode',
            field=models.CharField(max_length=250, null=True, verbose_name='postcode'),
        ),
        migrations.AddField(
            model_name='contact',
            name='street',
            field=models.CharField(max_length=250, null=True, verbose_name='street name'),
        ),
        migrations.AddField(
            model_name='contact',
            name='town',
            field=models.CharField(max_length=250, null=True, verbose_name='town and county'),
        ),
    ]
