# Generated by Django 4.0.2 on 2022-02-06 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0034_contact_building_alter_contact_country_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Header_Videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_video', models.FileField(null=True, upload_to='videos/', verbose_name='about video')),
            ],
        ),
    ]
