# Generated by Django 4.0.2 on 2022-02-06 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0036_about'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Header_Videos',
        ),
        migrations.AddField(
            model_name='about',
            name='header',
            field=models.FileField(null=True, upload_to='videos/', verbose_name='Header video'),
        ),
    ]
