# Generated by Django 4.0.2 on 2022-02-06 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0037_delete_header_videos_about_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='content',
            field=models.ImageField(null=True, upload_to='images/', verbose_name='content image'),
        ),
    ]
