# Generated by Django 4.0.2 on 2022-02-06 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0038_about_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='david',
            field=models.ImageField(null=True, upload_to='images/', verbose_name='david image'),
        ),
        migrations.AddField(
            model_name='about',
            name='george',
            field=models.ImageField(null=True, upload_to='images/', verbose_name='george image'),
        ),
        migrations.AddField(
            model_name='about',
            name='paul',
            field=models.ImageField(null=True, upload_to='images/', verbose_name='paul image'),
        ),
        migrations.AddField(
            model_name='about',
            name='richard',
            field=models.ImageField(null=True, upload_to='images/', verbose_name='richard image'),
        ),
    ]
