# Generated by Django 4.0.2 on 2022-02-06 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0039_about_david_about_george_about_paul_about_richard'),
    ]

    operations = [
        migrations.CreateModel(
            name='Our_Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.FileField(null=True, upload_to='videos/', verbose_name='Header video')),
            ],
        ),
    ]
