# Generated by Django 4.0.2 on 2022-02-07 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0040_our_work'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case_Studies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_text', models.CharField(max_length=130, null=True, verbose_name='project text')),
                ('project_image', models.ImageField(null=True, upload_to='images/', verbose_name='project image')),
                ('project_size', models.CharField(max_length=130, null=True, verbose_name='project size (-big/-wide/-horizontal or - for standard)')),
                ('project_services', models.CharField(max_length=130, null=True, verbose_name='project services (Software/Acoustics/AV Design)')),
            ],
        ),
    ]
