# Generated by Django 4.0.2 on 2022-02-07 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0041_case_studies'),
    ]

    operations = [
        migrations.AddField(
            model_name='case_studies',
            name='project_category',
            field=models.CharField(max_length=130, null=True, verbose_name='project category (Content/Audiovisual Design/Acoustics/Development/Experiential/Retail)'),
        ),
        migrations.AlterField(
            model_name='case_studies',
            name='project_size',
            field=models.CharField(max_length=130, null=True, verbose_name='project size (-big/-wide/-horizontal/-long or - for standard)'),
        ),
    ]
