# Generated by Django 4.0.2 on 2022-02-07 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0043_alter_case_studies_project_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='case_studies',
            name='project_01_image',
            field=models.ImageField(null=True, upload_to='images/', verbose_name='Section 01 image'),
        ),
        migrations.AddField(
            model_name='case_studies',
            name='project_01_intro',
            field=models.CharField(max_length=130, null=True, verbose_name='01-The Client intro text'),
        ),
        migrations.AddField(
            model_name='case_studies',
            name='project_01_main',
            field=models.CharField(max_length=500, null=True, verbose_name='01-The Client main text'),
        ),
        migrations.AddField(
            model_name='case_studies',
            name='project_02_image1',
            field=models.ImageField(null=True, upload_to='images/', verbose_name='Section 02 image1'),
        ),
        migrations.AddField(
            model_name='case_studies',
            name='project_02_image2',
            field=models.ImageField(null=True, upload_to='images/', verbose_name='Section 02 image2'),
        ),
        migrations.AddField(
            model_name='case_studies',
            name='project_02_image3',
            field=models.ImageField(null=True, upload_to='images/', verbose_name='Section 02 image3'),
        ),
        migrations.AddField(
            model_name='case_studies',
            name='project_02_intro',
            field=models.CharField(max_length=130, null=True, verbose_name='02-The Brief intro text'),
        ),
        migrations.AddField(
            model_name='case_studies',
            name='project_02_main',
            field=models.CharField(max_length=500, null=True, verbose_name='02-The Brief main text'),
        ),
        migrations.AddField(
            model_name='case_studies',
            name='project_03_intro',
            field=models.CharField(max_length=130, null=True, verbose_name='03-The Challenge intro text'),
        ),
        migrations.AddField(
            model_name='case_studies',
            name='project_03_main',
            field=models.CharField(max_length=500, null=True, verbose_name='03-The Challenge main text'),
        ),
        migrations.AddField(
            model_name='case_studies',
            name='project_04_intro',
            field=models.CharField(max_length=130, null=True, verbose_name='03-The Outcome intro text'),
        ),
        migrations.AddField(
            model_name='case_studies',
            name='project_04_main',
            field=models.CharField(max_length=500, null=True, verbose_name='03-The Outcome main text'),
        ),
        migrations.AddField(
            model_name='case_studies',
            name='project_05_link1',
            field=models.CharField(max_length=120, null=True, verbose_name='05 - link 1'),
        ),
        migrations.AddField(
            model_name='case_studies',
            name='project_05_link2',
            field=models.CharField(max_length=120, null=True, verbose_name='05 - link 2'),
        ),
        migrations.AddField(
            model_name='case_studies',
            name='project_05_link3',
            field=models.CharField(max_length=120, null=True, verbose_name='05 - link 3'),
        ),
        migrations.AddField(
            model_name='case_studies',
            name='project_06_link3',
            field=models.CharField(max_length=120, null=True, verbose_name='06 - manufacturer 3'),
        ),
        migrations.AddField(
            model_name='case_studies',
            name='project_client',
            field=models.CharField(max_length=130, null=True, verbose_name="client's name"),
        ),
        migrations.AddField(
            model_name='case_studies',
            name='project_duration',
            field=models.CharField(max_length=130, null=True, verbose_name='project duration'),
        ),
        migrations.AddField(
            model_name='case_studies',
            name='project_header',
            field=models.ImageField(null=True, upload_to='images/', verbose_name='case study header image'),
        ),
    ]
