# Generated by Django 4.0.2 on 2022-02-07 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0046_alter_case_studies_project_03_main_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case_studies',
            name='project_02_main',
            field=models.CharField(max_length=850, null=True, verbose_name='02-The Brief main text'),
        ),
    ]
