# Generated by Django 4.0.2 on 2022-02-08 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0050_alter_case_studies_project_02_main_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='case_studies',
            name='video_checkbox',
            field=models.BooleanField(blank=True, default=0, null=True, verbose_name='is this a video? (y/n)'),
        ),
    ]
