# Generated by Django 4.0.2 on 2022-02-08 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0051_case_studies_video_checkbox'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case_studies',
            name='project_01_intro',
            field=models.CharField(blank=True, max_length=130, null=True, verbose_name='01-The Client intro text'),
        ),
        migrations.AlterField(
            model_name='case_studies',
            name='project_01_main',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='01-The Client main text'),
        ),
        migrations.AlterField(
            model_name='case_studies',
            name='project_02_image1',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Section 02 image1'),
        ),
        migrations.AlterField(
            model_name='case_studies',
            name='project_02_image2',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Section 02 image2'),
        ),
        migrations.AlterField(
            model_name='case_studies',
            name='project_02_image3',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Section 02 image3'),
        ),
        migrations.AlterField(
            model_name='case_studies',
            name='project_02_intro',
            field=models.CharField(blank=True, max_length=130, null=True, verbose_name='02-The Brief intro text'),
        ),
        migrations.AlterField(
            model_name='case_studies',
            name='project_02_main',
            field=models.CharField(blank=True, max_length=1450, null=True, verbose_name='02-The Brief main text'),
        ),
        migrations.AlterField(
            model_name='case_studies',
            name='project_03_intro',
            field=models.CharField(blank=True, max_length=130, null=True, verbose_name='03-The Challenge intro text'),
        ),
        migrations.AlterField(
            model_name='case_studies',
            name='project_03_main',
            field=models.CharField(blank=True, max_length=1450, null=True, verbose_name='03-The Challenge main text'),
        ),
        migrations.AlterField(
            model_name='case_studies',
            name='project_04_intro',
            field=models.CharField(blank=True, max_length=130, null=True, verbose_name='03-The Outcome intro text'),
        ),
        migrations.AlterField(
            model_name='case_studies',
            name='project_04_main',
            field=models.CharField(blank=True, max_length=1450, null=True, verbose_name='03-The Outcome main text'),
        ),
        migrations.AlterField(
            model_name='case_studies',
            name='project_05_link1',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='05 - link 1'),
        ),
        migrations.AlterField(
            model_name='case_studies',
            name='project_05_link2',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='05 - link 2'),
        ),
        migrations.AlterField(
            model_name='case_studies',
            name='project_05_link3',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='05 - link 3'),
        ),
        migrations.AlterField(
            model_name='case_studies',
            name='project_06_link1',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='06 - manufacturer 1'),
        ),
        migrations.AlterField(
            model_name='case_studies',
            name='project_06_link2',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='06 - manufacturer 2'),
        ),
        migrations.AlterField(
            model_name='case_studies',
            name='project_06_link3',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='06 - manufacturer 3'),
        ),
        migrations.AlterField(
            model_name='case_studies',
            name='project_category',
            field=models.CharField(blank=True, max_length=130, null=True, verbose_name='project category (content/AV/acoustics/development/experiential/retail)'),
        ),
        migrations.AlterField(
            model_name='case_studies',
            name='project_client',
            field=models.CharField(blank=True, max_length=130, null=True, verbose_name="client's name"),
        ),
        migrations.AlterField(
            model_name='case_studies',
            name='project_duration',
            field=models.CharField(blank=True, max_length=130, null=True, verbose_name='project duration'),
        ),
        migrations.AlterField(
            model_name='case_studies',
            name='project_header',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='case study header image'),
        ),
        migrations.AlterField(
            model_name='case_studies',
            name='project_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='project image'),
        ),
        migrations.AlterField(
            model_name='case_studies',
            name='project_services',
            field=models.CharField(blank=True, max_length=130, null=True, verbose_name='project services (Software/Acoustics/AV Design)'),
        ),
        migrations.AlterField(
            model_name='case_studies',
            name='project_size',
            field=models.CharField(blank=True, max_length=130, null=True, verbose_name='project size (-big/-wide/-horizontal/-long or - for standard)'),
        ),
        migrations.AlterField(
            model_name='case_studies',
            name='project_text',
            field=models.CharField(blank=True, max_length=130, null=True, verbose_name='project text'),
        ),
        migrations.AlterField(
            model_name='case_studies',
            name='video_checkbox',
            field=models.BooleanField(blank=True, default=0, verbose_name='is this a video? (y/n)'),
        ),
    ]
