# Generated by Django 4.0.2 on 2022-02-08 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0054_alter_case_studies_project_01_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case_studies',
            name='project_01_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Section 01 image'),
        ),
        migrations.AlterField(
            model_name='case_studies',
            name='project_02_image1',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Section 02 image1'),
        ),
        migrations.AlterField(
            model_name='case_studies',
            name='project_02_image2',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Section 02 image2'),
        ),
        migrations.AlterField(
            model_name='case_studies',
            name='project_02_image3',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Section 02 image3'),
        ),
    ]
