# Generated by Django 4.0.2 on 2022-02-08 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0055_alter_case_studies_project_01_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping', models.BooleanField()),
                ('shipping_destination', models.CharField(blank=True, choices=[('residential', 'Residential'), ('commercial', 'Commercial')], max_length=15)),
            ],
        ),
    ]
