# Generated by Django 4.0.2 on 2022-02-08 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0056_shippinginfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShippingInfo',
        ),
    ]
