# Generated by Django 4.0.2 on 2022-02-08 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0059_remove_case_studies_project_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='case_studies',
            name='project_header',
            field=models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='case study header video'),
        ),
        migrations.AlterField(
            model_name='case_studies',
            name='video_checkbox',
            field=models.BooleanField(blank=True, default=1, verbose_name='is this a video? (y/n)'),
        ),
    ]
