# Generated by Django 4.0.2 on 2022-02-08 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0061_alter_case_studies_project_header'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case_studies',
            old_name='project_header',
            new_name='project_header_image',
        ),
        migrations.AddField(
            model_name='case_studies',
            name='project_header_video',
            field=models.FileField(null=True, upload_to='videos/', verbose_name='case study header video'),
        ),
    ]
