# Generated by Django 4.0.2 on 2022-02-08 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0062_rename_project_header_case_studies_project_header_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case_studies',
            name='video_checkbox',
            field=models.BooleanField(blank=True, default=1, verbose_name='Choose video for header (y/n)'),
        ),
    ]
