# Generated by Django 4.0.2 on 2022-02-08 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0063_alter_case_studies_video_checkbox'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case_studies',
            name='project_header_video',
            field=models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='case study header video'),
        ),
    ]
