# Generated by Django 4.0.2 on 2022-02-08 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0064_alter_case_studies_project_header_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case_studies',
            name='project_01_intro',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='01-The Client intro text'),
        ),
    ]
