# Generated by Django 4.0.2 on 2022-02-08 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0065_alter_case_studies_project_01_intro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case_studies',
            name='project_01_intro',
            field=models.CharField(blank=True, max_length=130, null=True, verbose_name='01-The Client intro text'),
        ),
        migrations.AlterField(
            model_name='case_studies',
            name='project_01_main',
            field=models.CharField(blank=True, max_length=750, null=True, verbose_name='01-The Client main text'),
        ),
    ]
