# Generated by Django 4.0.2 on 2022-02-10 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0067_lab_headervideo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lab',
            old_name='image',
            new_name='title_image',
        ),
        migrations.RemoveField(
            model_name='lab',
            name='headervideo',
        ),
        migrations.AddField(
            model_name='lab',
            name='title_video',
            field=models.FileField(null=True, upload_to='videos/', verbose_name='Main Video'),
        ),
        migrations.AddField(
            model_name='lab',
            name='video_checkbox',
            field=models.BooleanField(blank=True, default=1, verbose_name='is this a video? (y/n)'),
        ),
    ]
