# Generated by Django 4.0.2 on 2022-02-10 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0068_rename_image_lab_title_image_remove_lab_headervideo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab',
            name='description1',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Main description text'),
        ),
        migrations.AlterField(
            model_name='lab',
            name='description2',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Secondary description text'),
        ),
        migrations.AlterField(
            model_name='lab',
            name='description3',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Conclusion text'),
        ),
        migrations.AlterField(
            model_name='lab',
            name='summary',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Main Summary text'),
        ),
        migrations.AlterField(
            model_name='lab',
            name='title_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Main Image'),
        ),
        migrations.AlterField(
            model_name='lab',
            name='title_video',
            field=models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='Main Video'),
        ),
        migrations.AlterField(
            model_name='lab',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='video 1'),
        ),
        migrations.AlterField(
            model_name='lab',
            name='video2',
            field=models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='video 2'),
        ),
    ]
