# Generated by Django 4.0.2 on 2022-02-10 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0070_remove_lab_summary_lab_main_summary_lab_sub_summary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lab',
            old_name='main_summary',
            new_name='summary',
        ),
    ]
