# Generated by Django 4.0.2 on 2022-02-10 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0071_rename_main_summary_lab_summary'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lab',
        ),
    ]
