# Generated by Django 4.0.2 on 2022-02-10 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0072_delete_lab'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(blank=True, max_length=100, null=True, verbose_name='Main Summary text')),
                ('sub_summary', models.CharField(blank=True, max_length=200, null=True, verbose_name='Sub Summary text')),
                ('title_image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Main Image')),
                ('title_video', models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='Main Video')),
                ('video_checkbox', models.BooleanField(blank=True, default=1, verbose_name='is this a video? (y/n)')),
                ('description1', models.CharField(blank=True, max_length=500, null=True, verbose_name='Main description text')),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='video 1')),
                ('description2', models.CharField(blank=True, max_length=500, null=True, verbose_name='Secondary description text')),
                ('video2', models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='video 2')),
                ('description3', models.CharField(blank=True, max_length=500, null=True, verbose_name='Conclusion text')),
            ],
        ),
    ]
