# Generated by Django 4.0.2 on 2022-02-10 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0073_lab'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='description4',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Conclusion text'),
        ),
        migrations.AddField(
            model_name='lab',
            name='video3',
            field=models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='video 3'),
        ),
        migrations.AlterField(
            model_name='lab',
            name='description2',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Second section text'),
        ),
        migrations.AlterField(
            model_name='lab',
            name='description3',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Third Section Text'),
        ),
    ]
