# Generated by Django 4.0.2 on 2022-03-11 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0074_lab_description4_lab_video3_alter_lab_description2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='case_studies',
            name='project_05_hyperlink1',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='05 - Hyperlink1'),
        ),
        migrations.AddField(
            model_name='case_studies',
            name='project_05_hyperlink2',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='05 - Hyperlink 2'),
        ),
        migrations.AddField(
            model_name='case_studies',
            name='project_05_hyperlink3',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='05 - Hyperlink 3'),
        ),
        migrations.AddField(
            model_name='case_studies',
            name='project_06_Hyperlink1',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='06 - Hyperlink1'),
        ),
        migrations.AddField(
            model_name='case_studies',
            name='project_06_Hyperlink2',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='06 - Hyperlink2'),
        ),
        migrations.AddField(
            model_name='case_studies',
            name='project_06_Hyperlink3',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='06 - Hyperlink3'),
        ),
    ]
