# Generated by Django 4.0.2 on 2022-03-14 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0075_case_studies_project_05_hyperlink1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='case_studies',
            name='project_complete',
            field=models.BooleanField(blank=True, default=1, verbose_name='Is this Case Study Complete? (y/n)'),
        ),
    ]
