# Generated by Django 4.0.2 on 2022-03-14 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0078_case_studies_project_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case_studies',
            name='project_publish',
        ),
        migrations.RemoveField(
            model_name='case_studies',
            name='project_test',
        ),
    ]
